version: '3.1'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_USER=freelancer
      - MYSQL_PASSWORD=password
  adminer:
    image: adminer
    ports:
      - 8082:8080
volumes:
  data:
